### PR TITLE
Speed up and slim down the specializer; add profiling

### PR DESCRIPTION
**Pull request by rrthomas**
Also rationalise the way that various execution options (profiling,
predictor, specializer) are accessed.

### CODE REVIEW

**Comment by rrthomas** [comment]
TODO: update APIs in Python binding. (DONE)

**Comment by apt1002** [comment]
In commit "Add --predictor to mit (fix #273)" a new predictor file was checked in by accident. Remove it!

**Comment by apt1002** [comment]
The predictor now allocates 2Gb, which is TOO MUCH. Feed it the actual number of opcodes.

Since we're doing this, also put the Python bindings for the profiler into a separate commit.

**Review by apt1002 — APPROVED** [review]
All looks good. Approved with some comments.

**Pull request merged**
