### PR TITLE
Finesse the instruction set as far as I can satisfactorily

### PR DESCRIPTION
**Pull request by rrthomas**
Add variable-size LOAD/STORE.

In the end, I did not find a satisfactory solution for either immediate
operands or small literals (which are really another case of immediate
operands).

### CODE REVIEW

**Comment by apt1002** [comment]
"Words are {\tt WORD\_BYTES} bytes." <-- Maybe add "WORD_BYTES is usually 4 or 8". The main benefit is to save the user from working out that WORD_BYTES is a symbolic constant, and the secondary benefit is to indicate why you felt that a symbolic constant was useful here.

**Comment by apt1002** [comment]
"Before SMite is started, ENDISM should be set" <-- By whom? This is an odd way to phrase it. It makes it look like this is something I have to take care over when I create a smite_state.

I suggest something like "An implementation of Smite must hard-wire ENDISM and WORD_BYTES to describe itself". This text, and "ENDISM and WORD_BYTES must not change" should perhaps be in the Registers section, not the Operation section.

**Comment by apt1002** [comment]
"Invalid size (greater than log 2 WORD_BYTES)." <-- Use the `\log` command, not `l o g`. But brackets around "WORD_BYTES".

"an integer in the range 0 to log 2 WORD_BYTES inclusive." <-- Ditto.

**Comment by rrthomas** [comment]
> "Invalid size (greater than log 2 WORD_BYTES)." <-- Use the `\log` command, not `l o g`. But brackets around "WORD_BYTES".
> 
> "an integer in the range 0 to log 2 WORD_BYTES inclusive." <-- Ditto.

Thanks; I used `\log` but did not add parentheses, as they don't seem to add anything.

Note that for ease of reference you can comment on the actual file in the commit, rather than just appending notes to the PR.

**Comment by apt1002** [comment]
(Should have been a comment on an earlier pull request, sorry).

"where the i k are stack items, each of which occupies a whole number of words" <-- I'm a bit confused about the distinction between a stack item and a word. Table 3 includes several types that could conceivably occupy more than one word, including "n", "u", "addr" and "a-addr". Table 4 reveals that all of these are subtypes of "x", which implies that they must be one-word quantities, and you also say "Ellipsis is used for indeterminate numbers of specified types of word" (not "types of item").

Rereading section "Stack", I notice that pushing an item increases the stack depth by 1, and that the stack is a stack of words, which also implies that an item must be a word.

I know it is your intention that stack pictures not in the spec can mention items that occupy more than one word, and I think this has probably infected the spec. If it is your intention that all items mentioned in the spec are one-word quantities, I suggest you standardise the terminology (i.e. use only one of "word" or "item") to avoid setting the reader a futile challenge. Alternatively, if you want to use "item" to mean a word that is on the stack, don't say that it can be more than one word in size.

**Comment by apt1002** [comment]
(This should have been a comment on an earlier pull request, sorry).

"add WORD_BYTES to PC. If PC is not word-aligned, raise error 7" <-- Maybe exchange these sentences? I know it makes no difference because the exception will unwind the add, but new readers might not.

**Comment by rrthomas** [comment]
>  Table 3 includes several types that could conceivably occupy more than one word, including "n", "u", "addr" and "a-addr". Table 4 reveals that all of these are subtypes of "x", which implies that they must be one-word quantities, and you also say "Ellipsis is used for indeterminate numbers of specified types of word" (not "types of item").

That's correct. All of these types cannot conceivably occupy more than a word. They are all defined as being a word in size.

> Alternatively, if you want to use "item" to mean a word that is on the stack, don't say that it can be more than one word in size.

That's what I would rather do: an item should be a scalar on the stack with a name (possibly more than one word). I'll fix references to this and add a definition. Thanks!

**Comment by apt1002** [comment]
(Again not this pull request, sorry).

"If flag is false then set PC to a-addr" <-- If "flag" is 2, can the implementation interpret that as "false"?. The implementation treats all non-zero values as "true", but a close reading of the spec does not define how to interpret an item typed "flag" unless it is zero or one.

**Comment by apt1002** [comment]
"which must be a multiple of size." (two occurrences) <-- "size" should be "2^size".

**Comment by apt1002** [comment]
```
\opcodetblone{0c}{LSHIFT}	{1c}{LIT\_0}
\opcodetblone{0d}{RSHIFT}	{1d}{LIT\_1}
```

These should use `\opcodetbl`.

**Comment by apt1002** [comment]
The load/store design is really good.

**Comment by apt1002** [comment]
smite.h:

`return (addr + (1 << size) - 1) & -(1 << size);` <-- Maybe put brackets around the constant `(1 << size) - 1`?

**Comment by apt1002** [comment]
smite.h: smite_load()

```
/* Copy `size` bytes from `addr` to `val_ptr`.
```

`size` should be `1<<size`, and there are consequential errors throughout the comment.

smite_store() has the same error.

**Comment by apt1002** [comment]
Thanks for making `memory`, `memory_size`, `stack` and `stack_size` not be registers.

**Comment by apt1002** [comment]
smite_realloc() and friends: I suggest you document that the size is specified in words, not bytes.

**Comment by apt1002** [comment]
tests/errors.py

```
lit(VM.memory_size * word_bytes + 1)
```

The multiplication by word_bytes is unnecessary and confusing. It has already been done.

**Review by apt1002 — DISMISSED** [review]
There's some good stuff in here. Approved subject to comments.

**Comment by apt1002** [comment]
I used \log but did not add parentheses <-- I think you did this on the wrong branch?

**Comment by rrthomas** [comment]
`\log` fix cherry-picked to correct branch.

**Comment by rrthomas** [comment]
`VM.memory_size` is indeed in words.

**Comment by rrthomas** [comment]
I have pushed fixes to all of the comments now. Please re-review, @apt1002!

**Comment by apt1002** [comment]
smite.pdf: Execution

"In the latter case, the contents of the execution cycle is executed once, and
control returns to the calling program." <-- What latter case?

**Comment by apt1002** [comment]
smite.pdf: Architecture

"These parameters enable efficient implementation
on the vast majority of machine architectures." <-- What parameters?

**Comment by apt1002** [comment]
smite.pdf: Table "types used in stack effects".

"an integer in the range 0 to log 2 WORD_BYTES inclusive." <-- Only this item ends with a full stop.

**Comment by apt1002** [comment]
smite.pdf: Execution

"execute the instruction in the 8 least-significant bits of I
shift I logically 8 bits to the right" <-- I think it is important that the shift occurs before executing the instruction.

**Review by apt1002 — APPROVED** [review]
Approved.

**Comment by rrthomas** [comment]
> "execute the instruction in the 8 least-significant bits of I
> shift I logically 8 bits to the right" <-- I think it is important that the shift occurs before executing the instruction.

I don't understand this: if the shift occurs before the instruction is executed, then it isn't undone if the instruction raises an error. Please could you explain further?

**Comment by apt1002** [comment]
Shift before execute: Consider the action of `BRANCH`, for example. If the bottom 8 bits of `I` encode `BRANCH` then `I` is non-zero so `BRANCH` must report a bad encoding. And if it doesn't and instead refills `I` then the first instruction from the new location will be lost when `I` is shifted right by 8 places. I think you need to document that errors unwind side-effects separately, if you haven't already.

**Comment by rrthomas** [comment]
I think I have a better solution: currently, the semantics of `NEXT` is performed by some instructions, while all the rest effectively do the shift of `I`. Instead, let's put both of those in the execution loop: after executing an instruction, shift `I`, then if it's now zero, load `I` from `PC`.

The error check that `I` is 0 after a terminal instruction is added to those instructions; in `BRANCHZ` instead, we explicitly set `I` to 0.

`NEXT` becomes `NOP` and there's no longer any need for the `auto_NEXT` hack in `step`.

**Pull request merged**
